# Generated by Django 2.0.13 on 2019-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190409_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='pages.Post'),
            preserve_default=False,
        ),
    ]
